---

stages:
  - lint

lint-docker-composes:
  stage: lint
  image: registry.gitlab.com/pipeline-components/yamllint:latest
  script:
    - yamllint .gitlab-ci.yml docker-compose.*

lint-dockerfiles:
  stage: lint
  image: hadolint/hadolint:latest-debian
  script:
    - hadolint --ignore DL3008 --ignore DL3006 docker/Dockerfile.example
    - hadolint --ignore DL3008 --ignore DL3006 docker/baseimg/Dockerfile
